In [17]:
import numpy as np
import pandas as pd

In [26]:
import pandas as pd
path = 'superstore dataset/Sample - Superstore.csv'
data = pd.read_csv(path)

In [136]:
df = data.copy()

In [137]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [138]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [139]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [140]:
df.columns = df.columns.str.lower().str.replace(' ', '_')
df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,postal_code,region,product_id,category,sub-category,product_name,sales,quantity,discount,profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [141]:
for date in df['order_date']:
    df['order_date'] = pd.to_datetime(date).strftime('%Y-%m-%d')    
print("All order dates have been converted to YYYY-MM-DD format.")

for date in df['ship_date']:
    df['ship_date'] = pd.to_datetime(date).strftime('%Y-%m-%d')
print("All ship dates have been converted to YYYY-MM-DD format.")

All order dates have been converted to YYYY-MM-DD format.
All ship dates have been converted to YYYY-MM-DD format.

In [142]:
df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,postal_code,region,product_id,category,sub-category,product_name,sales,quantity,discount,profit
0,1,CA-2016-152156,2017-05-04,2017-05-09,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2017-05-04,2017-05-09,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2017-05-04,2017-05-09,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2017-05-04,2017-05-09,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2017-05-04,2017-05-09,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [144]:
max_lengths = df.astype(str).map(len).max()
print(max_lengths)

row_id             4
order_id          14
order_date        10
ship_date         10
ship_mode         14
customer_id        8
customer_name     22
segment           11
country           13
city              17
state             20
postal_code        5
region             7
product_id        15
category          15
sub-category      11
product_name     127
sales              9
quantity           2
discount           4
profit            10
dtype: int64

In [145]:
df.replace("'", "''", regex=True, inplace=True)

In [149]:
df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,postal_code,region,product_id,category,sub-category,product_name,sales,quantity,discount,profit
0,1,CA-2016-152156,2017-05-04,2017-05-09,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2017-05-04,2017-05-09,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2017-05-04,2017-05-09,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2017-05-04,2017-05-09,Standard Class,SO-20335,Sean O''Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2017-05-04,2017-05-09,Standard Class,SO-20335,Sean O''Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold ''N Roll Cart System,22.3680,2,0.20,2.5164

In [150]:
df.duplicated().sum()

np.int64(0)

In [147]:
df.isnull().sum()

row_id           0
order_id         0
order_date       0
ship_date        0
ship_mode        0
customer_id      0
customer_name    0
segment          0
country          0
city             0
state            0
postal_code      0
region           0
product_id       0
category         0
sub-category     0
product_name     0
sales            0
quantity         0
discount         0
profit           0
dtype: int64

In [151]:
df.index

RangeIndex(start=0, stop=9994, step=1)

In [152]:
df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,postal_code,region,product_id,category,sub-category,product_name,sales,quantity,discount,profit
0,1,CA-2016-152156,2017-05-04,2017-05-09,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2017-05-04,2017-05-09,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2017-05-04,2017-05-09,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2017-05-04,2017-05-09,Standard Class,SO-20335,Sean O''Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2017-05-04,2017-05-09,Standard Class,SO-20335,Sean O''Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold ''N Roll Cart System,22.3680,2,0.20,2.5164

In [154]:
import re

# Define a function to check for problematic characters
def check_problematic_chars(value):
    if isinstance(value, str):
        return bool(re.search(r"[\'\"\\]", value))
    return False

# Apply the function to the dataframe and get the problematic values
problematic_values = df.applymap(check_problematic_chars)

# Get the rows and columns with problematic values
rows_with_issues = problematic_values.any(axis=1)
columns_with_issues = problematic_values.any(axis=0)

# Display the problematic rows and columns
problematic_df = df.loc[rows_with_issues, columns_with_issues]
problematic_df

C:\Users\Kyle\AppData\Local\Temp\ipykernel_17776\4284915123.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  problematic_values = df.applymap(check_problematic_chars)

           customer_name                                       product_name
3        Sean O''Donnell      Bretford CR4500 Series Slim Rectangular Table
4        Sean O''Donnell                    Eldon Fold ''N Roll Cart System
16             Pete Kriz  Stur-D-Stor Shelving, Vertical 5-Shelf: 72"H x...
20    Zuschuss Donatelli        Wilson Jones Hanging View Binder, White, 1"
22             Ken Black       Acco Six-Outlet Power Strip, 4'' Cord Length
...                  ...                                                ...
9956       Kristina Nunn  Wirebound Message Books, Four 2 3/4" x 5" Form...
9963        Alan Shonely      Eureka Recycled Copy Paper 8 1/2" x 11", Ream
9982          Ryan Crowe  RSVP Cards & Envelopes, Blank White, 8-1/2" X ...
9985    Dianna Vittorini  Acme Hot Forged Carbon Steel Scissors with Nic...
9992         Dave Brooks  It''s Hot Message Books with Stickers, 2 3/4" ...

[1137 rows x 2 columns]

In [157]:
df.loc[668]

row_id                                                 669
order_id                                    CA-2014-156314
order_date                                      2017-05-04
ship_date                                       2017-05-09
ship_mode                                      First Class
customer_id                                       RP-19390
customer_name                                 Resi Pï¿½lking
segment                                           Consumer
country                                      United States
city                                             Cleveland
state                                                 Ohio
postal_code                                          44105
region                                                East
product_id                                 FUR-FU-10003096
category                                         Furniture
sub-category                                   Furnishings
product_name     Master Giant Foot Doorstop, Safety Yellow
sales                                                30.36
quantity                                                 5
discount                                               0.2
profit                                              8.7285
Name: 668, dtype: object

In [153]:
df.to_csv('cleaned_superstore_data.csv', index=False)